Title: Dissertation and Thesis Formatting: Tips for Successful Submission
Remote_theme: ubc-library-rc/rc-workshop-template
Footer_content: "<a href=\"https://github.com/ubc-library-rc/intro-citationmanagement/\">View workshop content in GitHub</a>"
